name: Afrelib
favicon: null
layout_spectrum: 0.5727241660933942
typography_spectrum: 0.8944272713270038
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.11221633711829782
  lightness: 0.46530224685557187
  saturation: 0.7479423400945961
  rhythmicContrast: 0.6929281803313643
purpose: []
