name: Afrelib
favicon: null
layout_spectrum: 0.996
typography_spectrum: 0.8944272713270038
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0065b5'
    - '#6496d2'
    - '#2f81c2'
    - '#cfe2f1'
  brandStrength: 1
  lightness: 0.46530224685557187
  saturation: 0.7479423400945961
  rhythmicContrast: 0.6929281803313643
purpose: []
