name: Afrelib
favicon: null
layout_spectrum: 0.97305
typography_spectrum: 0.59381
title: Creating 21st Century Teaching and Classrooms
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#009128'
    - '#80c156'
    - '#afdcbb'
    - '#47af64'
  brandStrength: 0
  lightness: 0.5625
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
